repositories:
  - prefix: bitnami
    urls:
      - https://charts.bitnami.com/bitnami
  - prefix: jetstack
    urls:
      - https://charts.jetstack.io
  - prefix: jenkins-x
    urls:
      - http://localhost:8088
  - prefix: stable
    urls:
      - https://kubernetes-charts.storage.googleapis.com
  - prefix: flagger
    urls:
      - https://flagger.app
